### ISSUE TITLE
lfilter fails on second GPU

### ISSUE THREAD

**Issue by nukelash** [pytorch/audio#3425]
### 🐛 Describe the bug

When I run torchaudio.functional.lfilter() on cuda:1, it fails after exactly 1022 iterations. It works as expected on cuda:0.
```
import torch
import torchaudio
from tqdm import tqdm

device = 'cuda:0'

for i in tqdm(range(2000)):
    t = torch.rand([8, 12000], device=device) - 0.5
    a = torch.rand([8, 3], device=device)
    b = torch.rand([8, 3], device=device)
    out = torchaudio.functional.lfilter(t, a, b)

device = 'cuda:1'

for i in tqdm(range(2000)):
    t = torch.rand([8, 12000], device=device) - 0.5
    a = torch.rand([8, 3], device=device)
    b = torch.rand([8, 3], device=device)
    out = torchaudio.functional.lfilter(t, a, b)
```
results in
```
Traceback (most recent call last):
  File "/path/to/lfilter_repro.py", line 19, in <module>
    out = torchaudio.functional.lfilter(t, a, b)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/python3.11/site-packages/torchaudio/functional/filtering.py", line 1060, in lfilter
    output = torch.clamp(output, min=-1.0, max=1.0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
If I run lfilter() with clamp=False, the error arrises the next time I do anything to the output (ex. out = out + 1)
pytorch 2.0.1+cu117
python 3.11
Tested on 2 machines, one with a pair of 2080tis and one with a pair of 3090s

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          20
On-line CPU(s) list:             0-19
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
Stepping:                        7
CPU MHz:                         3887.172
CPU max MHz:                     4700.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7399.70
Virtualization:                  VT-x
L1d cache:                       320 KiB
L1i cache:                       320 KiB
L2 cache:                        10 MiB
L3 cache:                        19.3 MiB
NUMA node0 CPU(s):               0-19
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi

**Comment by mthrok** [comment]
Hi @nukelash 

Thanks for the report. I could reproduce this. 

@yoyololicon  Do you have an idea what could be causing this?

```
100%|█████████████████████████████| 2000/2000 [00:26<00:00, 75.69it/s]
 51%|██████████████▌              | 1022/2000 [00:05<00:04, 196.90it/s]
Traceback (most recent call last):
  File "/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 937, in <module>
  File "__main__.py", line 934, in __invoke_main
  File "/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "repro_3425.py", line 19, in <module>
    out = torchaudio.functional.lfilter(t, a, b)
  File "torchaudio/functional/filtering.py", line 1060, in lfilter
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Device-side assertion tracking was not enabled by user.
```

**Comment by mthrok** [comment]
Further observation:

1. Enabling `CUDA_LAUNCH_BLOCKING=1`, the error is moved to the first iteration of the second loop.
1. The first loop is irrelevant. Skipping the first loop still causes the issue.
1. The loop is irrelevant.

The reproduction can be reduced to this.

```python
import os

os.environ["TORCH_CPP_SHOW_STACKTRACES"] = "1"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import torch
import torchaudio

device = "cuda:1"

t = torch.rand([8, 12000], device=device) - 0.5
a = torch.rand([8, 3], device=device)
b = torch.rand([8, 3], device=device)
out = torchaudio.functional.lfilter(t, a, b)
```

**Comment by yoyololicon** [comment]
Hi @nukelash @mthrok , thanks for reporting this.
It's a great check since I have only used `lfilter` on a single GPU in a single process before.
I think the problem is from the cuda code. 
I'll have a proper look next week cuz I just heading back from a conference.

**Comment by yoyololicon** [comment]
I think I found the solution. 
https://discuss.pytorch.org/t/c-cuda-extension-with-multiple-gpus/91241/6?u=yoyololicon
A device guard `OptionalCUDAGuard` is needed. Will work on it later.

**Comment by mthrok** [comment]
@nukelash The issue should be fixed on main branch, which will be available tomorrow's nightly build. Let us know if it still does not work.

**Comment by nukelash** [comment]
Looks like it's all working correctly now. Thanks a ton!
